services:
  database:
    image: postgres:alpine # Imagem oficial do PostgreSQL no Docker
    container_name: database
    restart: always
    env_file:
      - .env.docker # Carrega as variáveis de ambiente para o banco de dados também
    ports:
      - 5432:5432 # Usa a variável DB_PORT do .env
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistência dos dados do banco
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

